name: Run PowerShell Script with Module

on:
  push:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install the PowerShell module
      - name: Install PowerShell Module
        run: |
          Install-Module -Name Microsoft.PowerApps.Administration.PowerShell -Force -Scope CurrentUser
          Install-Module Microsoft.PowerApps.PowerShell -Force -Scope CurrentUser
          Install-Module Microsoft.Xrm.Data.PowerShell -Force -Scope CurrentUser
        shell: pwsh

      # Step 3: Import the PowerShell module and run the script
      - name: Run PowerShell Script
        run: |
         # Import-Module -Name ModuleName
          ./PowerPlatSampleScript.ps1
        shell: pwsh
