name: Run PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: ubuntu-latest # Or 'windows-latest' if you need a Windows environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./PowerPlatSampleScript.ps1 # Replace with your script's path
